export interface Product {
  id: string;
  name: string;
  description: string;
  category: string;
  brand: string;
  price_paise: number;
  sizes: string[];
  colors: string[];
  stock: number;
  tags: string[];
  image?: string;
  rating?: number;
  reviews_count?: number;
}

export const FOOTWEAR_PRODUCTS: Product[] = [
  {
    id: 'prod_001',
    name: 'Nike Revolution 6',
    description: 'Lightweight everyday running shoe with responsive foam cushioning. Breathable mesh upper keeps feet cool during long runs. Ideal for road running and gym workouts.',
    category: 'running-shoes',
    brand: 'Nike',
    price_paise: 249900,
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['black', 'white', 'blue'],
    stock: 12,
    tags: ['running', 'lightweight', 'road-running', 'gym', 'breathable'],
    image: '/assets/urbanstride/Shoe1.png',
    rating: 4.8,
    reviews_count: 328,
  },
  {
    id: 'prod_002',
    name: 'Adidas Lite Racer CLN 2.0',
    description: 'Clean and minimalist running shoe with Cloudfoam comfort. Perfect for casual runs and everyday wear. Slip-on design for easy on/off.',
    category: 'running-shoes',
    brand: 'Adidas',
    price_paise: 219900,
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['white', 'grey', 'black'],
    stock: 8,
    tags: ['running', 'casual', 'cloudfoam', 'slip-on', 'minimalist'],
    image: '/assets/urbanstride/Shoe2.png',
    rating: 4.7,
    reviews_count: 214,
  },
  {
    id: 'prod_003',
    name: 'Puma Velocity NITRO 2',
    description: 'High-performance running shoe with NITRO foam technology for maximum energy return. Designed for speed training and race-day performance.',
    category: 'running-shoes',
    brand: 'Puma',
    price_paise: 289900,
    sizes: ['7', '8', '9', '10'],
    colors: ['electric-blue', 'black', 'green'],
    stock: 5,
    tags: ['running', 'performance', 'nitro-foam', 'speed', 'race'],
    image: '/assets/urbanstride/Shoe3.png',
    rating: 4.9,
    reviews_count: 189,
  },
  {
    id: 'prod_004',
    name: 'Skechers GO RUN Consistent',
    description: 'Affordable and durable running shoe with responsive 5GEN cushioning. Great for beginners and everyday joggers. Machine washable upper.',
    category: 'running-shoes',
    brand: 'Skechers',
    price_paise: 179900,
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: ['navy', 'red', 'black'],
    stock: 20,
    tags: ['running', 'beginner', 'affordable', 'cushioning', 'everyday'],
    image: '/assets/urbanstride/Shoe4.png',
    rating: 4.6,
    reviews_count: 412,
  },
  {
    id: 'prod_005',
    name: 'Reebok Forever Floatride Energy 4',
    description: 'Premium running shoe with Floatride Energy foam for plush yet responsive cushioning. Ideal for long-distance running and marathon training.',
    category: 'running-shoes',
    brand: 'Reebok',
    price_paise: 269900,
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['white', 'orange', 'black'],
    stock: 7,
    tags: ['running', 'long-distance', 'marathon', 'premium', 'floatride'],
    image: '/assets/urbanstride/Image1.png',
    rating: 4.7,
    reviews_count: 98,
  },
  {
    id: 'prod_006',
    name: 'Under Armour Charged Rogue 3',
    description: 'Versatile running shoe with Charged Cushioning midsole. Great for track workouts, casual runs, and gym sessions. Durable rubber outsole.',
    category: 'running-shoes',
    brand: 'Under Armour',
    price_paise: 239900,
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['black', 'red', 'grey'],
    stock: 9,
    tags: ['running', 'versatile', 'gym', 'track', 'charged-cushioning'],
    image: '/assets/urbanstride/Image2.png',
    rating: 4.5,
    reviews_count: 142,
  },
  {
    id: 'prod_007',
    name: 'New Balance Fresh Foam 1080v13',
    description: 'Ultra-plush running shoe with Fresh Foam X midsole for a supremely cushioned ride. Top pick for long runs and recovery days.',
    category: 'running-shoes',
    brand: 'New Balance',
    price_paise: 349900,
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['blue', 'black', 'white'],
    stock: 4,
    tags: ['running', 'plush', 'long-run', 'recovery', 'ultra-cushioned'],
    image: '/assets/urbanstride/Image3.png',
    rating: 4.9,
    reviews_count: 276,
  },
  {
    id: 'prod_008',
    name: 'ASICS Gel-Nimbus 25',
    description: 'Top-of-the-line neutral running shoe with gel cushioning for maximum shock absorption. Recommended for overpronators and high-mileage runners.',
    category: 'running-shoes',
    brand: 'ASICS',
    price_paise: 379900,
    sizes: ['7', '8', '9', '10'],
    colors: ['black', 'white', 'silver'],
    stock: 0,
    tags: ['running', 'gel-cushioning', 'overpronation', 'high-mileage', 'neutral'],
    image: '/assets/urbanstride/Image4.png',
    rating: 4.8,
    reviews_count: 512,
  },
  {
    id: 'prod_009',
    name: "Nike Air Force 1 '07",
    description: 'The iconic all-white leather sneaker. Timeless silhouette with Air-Sole unit for everyday cushioning. A wardrobe essential.',
    category: 'casual-sneakers',
    brand: 'Nike',
    price_paise: 799900,
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['white', 'black', 'triple-white'],
    stock: 15,
    tags: ['casual', 'iconic', 'leather', 'everyday', 'classic', 'streetwear'],
    image: '/assets/urbanstride/Shoe1.png',
    rating: 5.0,
    reviews_count: 1420,
  },
  {
    id: 'prod_010',
    name: 'Adidas Superstar',
    description: 'Classic shell-toe sneaker with three stripes. Versatile street style icon since 1969. Leather upper with rubber outsole.',
    category: 'casual-sneakers',
    brand: 'Adidas',
    price_paise: 699900,
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['white-black', 'all-black', 'white-gold'],
    stock: 11,
    tags: ['casual', 'classic', 'shell-toe', 'three-stripes', 'streetwear'],
    image: '/assets/urbanstride/Shoe2.png',
    rating: 4.8,
    reviews_count: 890,
  },
  {
    id: 'prod_011',
    name: 'Puma Suede Classic XXI',
    description: 'Retro-inspired suede sneaker with softfoam comfort. A cult classic that transcends trends. Perfect for casual outings.',
    category: 'casual-sneakers',
    brand: 'Puma',
    price_paise: 499900,
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['navy-suede', 'red-suede', 'grey-suede'],
    stock: 8,
    tags: ['casual', 'suede', 'retro', 'classic', 'lifestyle'],
    image: '/assets/urbanstride/Shoe3.png',
    rating: 4.7,
    reviews_count: 420,
  },
  {
    id: 'prod_012',
    name: "Skechers D'Lites 4.0",
    description: 'Chunky-soled lifestyle sneaker with memory foam insole. Lightweight and comfortable for all-day wear.',
    category: 'casual-sneakers',
    brand: 'Skechers',
    price_paise: 389900,
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: ['white-gold', 'black-silver', 'white-pink'],
    stock: 18,
    tags: ['casual', 'chunky', 'memory-foam', 'lifestyle', 'comfortable'],
    image: '/assets/urbanstride/Shoe4.png',
    rating: 4.6,
    reviews_count: 310,
  },
  {
    id: 'prod_017',
    name: 'Woodland Waterproof Trekking Boot',
    description: 'Heavy-duty waterproof hiking boot with anti-skid rubber sole. Ideal for monsoon treks and rocky terrain. Nubuck leather upper with ankle support.',
    category: 'hiking-boots',
    brand: 'Woodland',
    price_paise: 499900,
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['brown', 'khaki', 'black'],
    stock: 10,
    tags: ['hiking', 'waterproof', 'trekking', 'nubuck', 'ankle-support'],
    image: '/assets/urbanstride/Image1.png',
    rating: 4.8,
    reviews_count: 670,
  },
  {
    id: 'prod_022',
    name: 'Wildcraft Tundra Trekking Shoe',
    description: 'Indian-made waterproof trekking shoe with reinforced toe cap and ankle support. Built for the Himalayas. Affordable alternative to international brands.',
    category: 'hiking-boots',
    brand: 'Wildcraft',
    price_paise: 299900,
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['green', 'grey', 'black'],
    stock: 16,
    tags: ['hiking', 'trekking', 'affordable', 'indian-brand', 'himalayan'],
    image: '/assets/urbanstride/Image2.png',
    rating: 4.7,
    reviews_count: 389,
  },
  {
    id: 'prod_023',
    name: 'HRX by Hrithik Roshan RUN',
    description: 'Indian performance running shoe with EVA cushioning. Designed for daily training. Lightweight and breathable at an accessible price point.',
    category: 'running-shoes',
    brand: 'HRX',
    price_paise: 149900,
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['black-red', 'blue-white', 'grey'],
    stock: 25,
    tags: ['running', 'indian-brand', 'affordable', 'eva-cushioning', 'training'],
    image: '/assets/urbanstride/Image3.png',
    rating: 4.5,
    reviews_count: 530,
  },
  {
    id: 'prod_024',
    name: 'Campus Hurricane',
    description: 'Budget-friendly running shoe with PU sole and mesh upper. Great for light jogging and school sports. Available in a wide size range.',
    category: 'running-shoes',
    brand: 'Campus',
    price_paise: 99900,
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: ['white', 'blue', 'black'],
    stock: 30,
    tags: ['running', 'budget', 'jogging', 'school-sports', 'pu-sole'],
    image: '/assets/urbanstride/Image4.png',
    rating: 4.4,
    reviews_count: 720,
  },
  {
    id: 'prod_025',
    name: 'Brooks Ghost 15',
    description: 'Balanced, smooth-riding neutral running shoe with DNA LOFT v2 cushioning. A trusted daily trainer for all paces. Brooks flagship neutral shoe.',
    category: 'running-shoes',
    brand: 'Brooks',
    price_paise: 319900,
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['electric-blue', 'grey', 'black-red'],
    stock: 3,
    tags: ['running', 'neutral', 'daily-trainer', 'balanced', 'dna-loft'],
    image: '/assets/urbanstride/Shoe1.png',
    rating: 4.9,
    reviews_count: 850,
  },
];
