export interface Product {
  id: string;
  name: string;
  description: string;
  category: string;
  brand: string;
  price_paise: number;
  sizes: string[];
  colors: string[];
  stock: number;
  tags: string[];
  image?: string;
  rating?: number;
  reviews_count?: number;
}

export const ELECTRONICS_PRODUCTS: Product[] = [
  {
    id: 'elec_001',
    name: 'boAt Rockerz 450 Pro',
    description: 'Wireless on-ear headphones with 70 hours playback and ASAP charge technology. Deep bass and comfortable earcups for prolonged listening.',
    category: 'electronics',
    brand: 'boAt',
    price_paise: 149900,
    sizes: ['onesize'],
    colors: ['black', 'blue', 'hazel-beige'],
    stock: 25,
    tags: ['headphones', 'wireless', 'bass', 'cheap', 'long-battery'],
    image: '/assets/techcart/headphones.jpg',
    rating: 4.6,
    reviews_count: 512,
  },
  {
    id: 'elec_002',
    name: 'OnePlus Nord Buds 2r',
    description: 'True wireless in-ear earbuds with 12.4mm dynamic drivers and dual mic design for clear calls. IP55 water and sweat resistance.',
    category: 'electronics',
    brand: 'OnePlus',
    price_paise: 219900,
    sizes: ['onesize'],
    colors: ['grey', 'blue'],
    stock: 18,
    tags: ['earbuds', 'wireless', 'oneplus', 'tws', 'sweatproof'],
    image: '/assets/techcart/earbuds.jpg',
    rating: 4.8,
    reviews_count: 380,
  },
  {
    id: 'elec_003',
    name: 'Sony WH-CH720N Noise Cancelling',
    description: 'Sony lightest wireless noise-cancelling overhead headphones. Equipped with Dual Noise Sensor technology and V1 processor.',
    category: 'electronics',
    brand: 'Sony',
    price_paise: 999000,
    sizes: ['onesize'],
    colors: ['black', 'blue', 'white'],
    stock: 6,
    tags: ['headphones', 'sony', 'noise-cancelling', 'premium', 'wireless'],
    image: '/assets/techcart/headphones.jpg',
    rating: 4.9,
    reviews_count: 670,
  },
  {
    id: 'elec_004',
    name: 'Noise ColorFit Pulse 3',
    description: 'Smart watch with 1.96" TFT display, Bluetooth calling, heart rate tracker, SpO2 sensor, and 150+ watch faces.',
    category: 'electronics',
    brand: 'Noise',
    price_paise: 139900,
    sizes: ['onesize'],
    colors: ['black', 'pink', 'silver'],
    stock: 0, // Intentionally Out of stock for testing stock-out logic!
    tags: ['smartwatch', 'bluetooth-calling', 'fitness', 'cheap'],
    image: '/assets/techcart/smartwatch.jpg',
    rating: 4.4,
    reviews_count: 920,
  },
  {
    id: 'elec_005',
    name: 'Fire-Boltt Gladiator',
    description: '1.96" Bluetooth calling smartwatch with rotating crown, luxury metal finish, 123 sports modes, and voice assistant support.',
    category: 'electronics',
    brand: 'Fire-Boltt',
    price_paise: 249900,
    sizes: ['onesize'],
    colors: ['black', 'gold', 'orange'],
    stock: 14,
    tags: ['smartwatch', 'calling', 'metal', 'luxury', 'assistant'],
    image: '/assets/techcart/smartwatch.jpg',
    rating: 4.7,
    reviews_count: 410,
  },
  {
    id: 'elec_006',
    name: 'Samsung Galaxy Watch 4 Classic',
    description: 'Premium smartwatch with physical rotating bezel, body composition analysis, sleep tracking, and Wear OS operating system.',
    category: 'electronics',
    brand: 'Samsung',
    price_paise: 449900,
    sizes: ['onesize'],
    colors: ['black', 'silver'],
    stock: 8,
    tags: ['smartwatch', 'samsung', 'wearos', 'premium', 'rotating-bezel'],
    image: '/assets/techcart/smartwatch.jpg',
    rating: 4.9,
    reviews_count: 830,
  },
  {
    id: 'elec_007',
    name: 'HP Wireless Keyboard & Mouse Combo 150',
    description: 'Ergonomic full-size keyboard and optical mouse combo. Simple plug-and-play setup with 2.4GHz wireless receiver.',
    category: 'electronics',
    brand: 'HP',
    price_paise: 129900,
    sizes: ['onesize'],
    colors: ['black'],
    stock: 22,
    tags: ['keyboard', 'mouse', 'wireless', 'hp', 'combo'],
    image: '/assets/techcart/keyboard.jpg',
    rating: 4.5,
    reviews_count: 240,
  },
  {
    id: 'elec_008',
    name: 'Logitech Pebble Keys 2 K380s',
    description: 'Multi-device Bluetooth wireless keyboard. Slim, portable design with scooped round keys and custom shortcut buttons.',
    category: 'electronics',
    brand: 'Logitech',
    price_paise: 299900,
    sizes: ['onesize'],
    colors: ['rose', 'tonal-graphite', 'off-white'],
    stock: 11,
    tags: ['keyboard', 'bluetooth', 'logitech', 'portable', 'minimalist'],
    image: '/assets/techcart/keyboard.jpg',
    rating: 4.8,
    reviews_count: 590,
  },
  {
    id: 'elec_009',
    name: 'Redragon K552 Mechanical Keyboard',
    description: 'RGB backlit mechanical gaming keyboard with dustproof red switches. Tenkeyless compact design with metal alloy chassis.',
    category: 'electronics',
    brand: 'Redragon',
    price_paise: 279900,
    sizes: ['onesize'],
    colors: ['black', 'white'],
    stock: 9,
    tags: ['keyboard', 'mechanical', 'gaming', 'rgb', 'tkl'],
    image: '/assets/techcart/keyboard.jpg',
    rating: 4.7,
    reviews_count: 320,
  },
];
